// ----------------------------------------------------------------------

export const role = [
  'Community Engagement Specialist',
  'Game Library Curator',
  'User Experience Designer',
  'Community Engagement Specialist',
  'Community Engagement Specialist',
  'Developer Relations Managerr',
  'Game Hosting Website Manager',
  'User Experience Designer',
  'Developer Relations Managerr',
  'ui designer',
  'ui/Community Engagement Specialist',
  'ui/Community Engagement Specialist',
  'ui designer',
  'User Experience Designer',
  'User Experience Designer',
  'front end developer',
  'User Experience Designer',
  'Game Library Curator',
  'full stack developer',
  'User Experience Designer',
  'Community Engagement Specialist',
  'ui designer',
  'Developer Relations Managerr',
  'ui/Community Engagement Specialist',
  'ui designer',
  'Developer Relations Managerr',
  'full stack developer',
  'hr manager',
  'hr manager',
  'ui/Community Engagement Specialist',
  'Developer Relations Managerr',
  'Game Library Curator',
  'ui designer',
  'Game Hosting Website Manager',
  'front end developer',
  'ui/Community Engagement Specialist',
  'Developer Relations Managerr',
  'ui/Community Engagement Specialist',
  'ui designer',
  'Game Library Curator',
];
