// ----------------------------------------------------------------------

export const title = [
  `Emerge: The Triad of Harmony Collection`,
  
];

export const sentence = [
  `Assumenda nam repudiandae rerum fugiat vel maxime.`,
  `Quis veniam aut saepe aliquid nulla.`,
  `Reprehenderit ut voluptas sapiente ratione nostrum est.`,
  `Error ut sit vel molestias velit.`,
  `Quo quia sit nihil nemo doloremque et.`,
  `Autem doloribus harum vero laborum.`,
  `Tempora officiis consequuntur architecto nostrum autem nam adipisci.`,
  `Voluptas sunt magni adipisci praesentium saepe.`,
  `Ea architecto quas voluptates voluptas earum illo est vel rem.`,
  `Ipsum expedita reiciendis ut.`,
  `Architecto vel voluptatibus alias a aut non maxime ipsa voluptates.`,
  `Reiciendis enim officiis cupiditate eaque distinctio laudantium modi similique consequatur.`,
  `Ab autem consequatur itaque mollitia ipsum cupiditate error repudiandae nobis.`,
  `Distinctio architecto debitis eligendi consequatur unde id modi accusantium possimus.`,
  `At ut voluptate accusantium.`,
  `Repudiandae ut qui veritatis sint.`,
  `Laboriosam blanditiis quo sed et qui esse ipsam necessitatibus sed.`,
  `Et molestiae et excepturi maxime omnis.`,
  `Sint dolorem quam eum magnam.`,
  `Rerum ut iusto iste quam voluptatem necessitatibus.`,
  `Et quam in.`,
  `Fugit esse tenetur.`,
  `Dolorem dolor porro nihil cupiditate molestiae deserunt ut.`,
  `Omnis beatae eos eius aut molestias laboriosam laborum et optio.`,
  `Ut veniam quam assumenda ut voluptatibus ducimus accusamus.`,
  `Quos dignissimos neque omnis reiciendis voluptatem ducimus.`,
  `Laboriosam quia ut esse.`,
  `Sit reiciendis nihil qui molestias et.`,
  `Facilis cupiditate minima ratione quaerat omnis velit non ex totam.`,
  `Provident sint esse voluptatem voluptas eveniet est.`,
  `Molestias consequatur ea facilis.`,
  `Tempora voluptatibus autem ut ut porro quae delectus dolorum.`,
  `Et consequatur amet nemo ducimus voluptatem placeat voluptas.`,
  `Modi iste atque hic voluptas sit quis deleniti quas consequatur.`,
  `Omnis est aliquid odio mollitia aliquid ex.`,
  `Officia possimus veniam quod molestias.`,
  `Mollitia inventore recusandae provident aut.`,
  `Numquam ullam beatae possimus.`,
  `Fuga velit cupiditate ex culpa odio aut ut.`,
  `Vero corrupti nam voluptatum excepturi est et.`,
];


export const Testimonialdescription = [
`Nice one`,`Cool Website`,`Smooth Platform`,`One of the best gaming website`,
`Nice one`,`Cool Website`,`Smooth Platform`,`One of the best gaming website`,
`Nice one`,`Cool Website`,`Smooth Platform`,`One of the best gaming website`,
`Nice one`,`Cool Website`,`Smooth Platform`,`One of the best gaming website`,
`Nice one`,`Cool Website`,`Smooth Platform`,`One of the best gaming website`,
`Nice one`,`Cool Website`,`Smooth Platform`,`One of the best gaming website`,
`Nice one`,`Cool Website`,`Smooth Platform`,`One of the best gaming website`,

]
export const rating = [
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  1,2,3,4,5,
  

];




export const Testimonialemail = [
  `krihslabasnet112@gmail.com`,
  `krihslab112@gmail.com`,
  `krihbasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslsnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihsasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `krihslabasnet112@gmail.com`,
  `Nice one`,
  `Cool Website`,
  `Smooth Platform`,
  `One of the best gaming website`,
  `Nice one`,
  `Cool Website`,
  `Smooth Platform`,
  `One of the best gaming website`,
  `Nice one`,
  `Cool Website`,
  `Smooth Platform`,
  `One of the best gaming website`,
  `Nice one`,
  `Cool Website`,
  `Smooth Platform`,
  `One of the best gaming website`,
  `Nice one`,
  `Cool Website`,
  `Smooth Platform`,
  `One of the best gaming website`,
  `Nice one`,
  `Cool Website`,
  `Smooth Platform`,
  `One of the best gaming website`,
  `Nice one`,
  `Cool Website`,
  `Smooth Platform`,
  `One of the best gaming website`,
];

export const description = [
  `To participate in an online game or tournament on our gaming website, you usually need to create an account and log in. Once logged in, you can browse the available games or tournaments, select the one you want to join, and follow the prompts to register or sign up. Depending on the specific game or tournament, there may be additional requirements, such as purchasing a ticket or meeting certain eligibility criteria.`,
  `The prizes or rewards for winning a tournament on our gaming website may vary depending on the specific tournament and game. They can include cash prizes, in-game currency, virtual items, or other types of rewards. The details of the prizes or rewards for each tournament are usually listed in the tournament rules or description.`,
  `If you encounter an issue or dispute during a tournament on our gaming website, you should contact the website's support or customer service team as soon as possible. Provide them with detailed information about the issue or dispute, including any relevant screenshots or evidence. The support team will investigate the matter and take appropriate actions to resolve the issue or dispute according to the website's policies and rules.`,
  `Yes, many tournaments hosted on gaming websites are open to both professional and casual gamers. Some tournaments may have different divisions or skill levels to accommodate players of various skill levels. It's important to review the tournament rules and requirements to determine if you are eligible to participate based on your gaming level or experience.`,
  `Some tournaments hosted on gaming websites may require an entry fee or charge for participation. This fee may be used to cover tournament costs, prize pools, or website maintenance. The entry fees or charges, if applicable, are usually listed in the tournament details or registration process. It's important to review and understand the fees or charges before participating in a tournament.`,
  `Depending on the tournament and game, there may be various ways to communicate with other players during the tournament, such as in-game chat, Discord, or other communication platforms. It's important to follow the tournament rules and guidelines for communication, and to be respectful and sportsmanlike when interacting with other players.`,
  `Streaming or recording tournament gameplay on our gaming website may be allowed, but it's important to review and adhere to the website's policies and rules regarding streaming or recording. Some tournaments may have specific guidelines or restrictions on streaming or recording gameplay to ensure fair competition and protect the integrity of the tournament.  `,
  `If you are unable to attend a scheduled tournament match on our gaming website, you should notify the tournament organizers or administrators as soon as possible. Depending on the specific tournament rules and circumstances, you may be disqualified from the tournament, or the match may be rescheduled. It's important to communicate promptly and follow the tournament rules for handling scheduling conflicts.`,
  `Eaque natus adipisci soluta nostrum dolorem. Nesciunt ipsum molestias ut aliquid natus ut omnis qui fugiat. Dolor et rem. Ut neque voluptatem blanditiis quasi ullam deleniti.`,
  `Nam et error exercitationem qui voluptate optio. Officia omnis qui accusantium ipsam qui. Quia sequi nulla perspiciatis optio vero omnis maxime omnis ipsum. Perspiciatis consequuntur asperiores veniam dolores.`,
  `Perspiciatis nulla ut ut ut voluptates totam consectetur eligendi qui. Optio ut cum. Dolorum sapiente qui laborum. Impedit temporibus totam delectus nihil. Voluptatem corrupti rem.`,
  `Distinctio omnis similique omnis eos. Repellat cumque rerum nisi. Reiciendis soluta non ut veniam temporibus. Accusantium et dolorem voluptas harum. Nemo eius voluptate dicta et hic nemo. Dolorem assumenda et beatae molestias sit quo mollitia quis consequatur.`,
  `Sed ut mollitia tempore ipsam et illum doloribus ut. Occaecati ratione veritatis explicabo. Omnis nam omnis sunt placeat tempore accusantium placeat distinctio velit.`,
  `Eum illo dicta et perspiciatis ut blanditiis eos sequi. Ea veritatis aut et voluptas aut. Laborum eos quia tempore a culpa.`,
  `Aut quos quae dolores repudiandae similique perferendis perferendis earum laudantium. Facere placeat natus nobis. Eius vitae ullam dolorem.`,
  `Vero dolorem et voluptatem fugit tempore a quam iure. Fuga consequatur corrupti sunt asperiores vitae. Libero totam repellendus animi debitis illum et sunt officia.`,
  `Cupiditate illum officiis id molestiae. Numquam non molestiae aliquid et natus sed hic. Alias quia explicabo sed corrupti sint. Natus in et odio qui unde facilis quia. Est sit eius laboriosam aliquid non aperiam quia quo corporis.`,
  `Et a ab. Optio aspernatur minus tempora amet vitae consectetur inventore cumque. Sed et omnis. Aspernatur a magnam.`,
  `Ipsum omnis et. Quia ea et autem tempore consequuntur veniam dolorem officiis. Ipsa dicta et ut quidem quia doloremque. Sequi vitae doloremque temporibus. Deserunt incidunt id aperiam itaque natus. Earum sit eaque quas incidunt nihil.`,
  `Quae consequatur reiciendis. Consequatur non optio. Eaque id placeat. Commodi quo officia aut repudiandae reiciendis tempore voluptatem et. Ut accusamus qui itaque maxime aliquam. Fugit ut animi molestiae porro maiores.`,
  `Modi hic asperiores ab cumque quam est aut. Voluptas atque quos molestias. Ut excepturi distinctio ipsam aspernatur sit.`,
  `Sunt totam facilis. Quam commodi voluptatem veniam. Tempora deleniti itaque fugit nihil voluptas.`,
  `Ipsam aliquam velit nobis repellendus officiis aut deserunt id et. Nihil sunt aut dolores aut. Dolores est ipsa quia et laborum quidem laborum accusamus id. Facilis odit quod hic laudantium saepe omnis nisi in sint. Sed cupiditate possimus id.`,
  `Magnam non eveniet optio optio ut aliquid atque. Velit libero aspernatur quis laborum consequatur laudantium. Tempora facere optio fugit accusantium ut. Omnis aspernatur reprehenderit autem esse ut ut enim voluptatibus.`,
  `Ipsam vel molestiae dolorem iure molestiae. Ut qui cumque et sint recusandae modi nulla. Vel rerum tempore similique autem enim voluptatem dolores facilis. Qui delectus recusandae magnam.`,
  `Fugiat molestias distinctio enim nobis rerum. Perspiciatis adipisci corrupti quas sed ab sunt nostrum. Quibusdam reiciendis ratione dolores vitae fuga exercitationem asperiores maxime voluptate. Minus et ea delectus quia ullam est. Exercitationem iusto libero. Et aut dolore reprehenderit et saepe sint modi.`,
  `Ex neque aut voluptatem delectus eum deserunt voluptate. Ut quam placeat et. Et impedit tenetur illum aut consequatur quia. Autem sed dolorem non ad aspernatur illum dignissimos beatae. Earum iusto aut rem aut. Facere ea alias enim quo assumenda.`,
  `Quis sint recusandae quasi corporis et fugit. Omnis voluptatum id laborum qui. Assumenda animi quia eum et facere fuga. Ab et sint molestiae et voluptatum nostrum est.`,
  `Est quis numquam recusandae alias porro magni. Incidunt quis aut necessitatibus nam ea dolores cumque. Quis dolorum veniam.`,
  `Corporis magnam non. Ut voluptates pariatur et. Quis tenetur mollitia et necessitatibus et. Perferendis error velit aut.`,
  `Eos ex accusantium possimus aut quae. Omnis dolorum velit. Sapiente quia dolore ea assumenda voluptatem exercitationem sed consequuntur. Eveniet et molestiae ipsa harum quidem soluta quo. Consequatur ad sunt sed numquam odio eveniet.`,
  `Ut sit et provident vero vero voluptatem distinctio. Cumque sit error qui et. Ea architecto ipsum occaecati sed alias eum vel. Officia tempore architecto autem vel veniam. Minus modi commodi ad consequatur similique ut. Tenetur tempore eum.`,
  `Quibusdam in cum voluptatem consequatur rerum. Qui eum assumenda nemo maiores veniam quae. Ipsa occaecati et provident. Quas similique deserunt doloremque placeat natus.`,
  `Voluptates et earum fugiat molestiae distinctio. Aut sapiente quas dolores et. Quo et dolor velit et iure consequatur ut in amet. Repellendus aut sequi animi inventore nesciunt itaque.`,
  `Sit a tempore dicta provident molestiae. Necessitatibus blanditiis voluptatum. Magnam esse animi in qui veritatis quibusdam recusandae adipisci possimus. Tenetur dolores ipsum.`,
  `Neque id sunt amet modi expedita aut libero aut in. Minima dolore praesentium quia quas et pariatur numquam. In ut sequi nemo velit iste minima aliquam. Neque ut tenetur consequuntur sint nemo unde. Magni nesciunt omnis illo optio. Molestias eum exercitationem aut harum odit.`,
  `Modi quia laboriosam qui ad aut. Fugit quisquam earum distinctio officia est fugit quos. Iure repellat distinctio veritatis voluptate amet ratione repudiandae.`,
  `Impedit perferendis vel quis ratione. Id aut id officia. Illum fuga saepe provident voluptate eligendi provident. Et nostrum maxime magni. Nobis cumque id magni in iste earum.`,
  `Dolor numquam maiores praesentium dolorem nihil minus praesentium rem dolorem. Est rerum placeat. Numquam sed magni aliquam laborum enim facere ducimus.`,
  `In sint enim nam et itaque et qui. Molestiae a iusto quidem quia temporibus id quia eaque eius. Quis quia consectetur saepe vero et molestias. Rem minima accusamus vitae adipisci molestiae unde voluptate consequatur molestiae. Rerum exercitationem quisquam vitae.`,
];

export const Privacydescription = [
  `We collect basic information such as your name, email address, and location. We may also collect additional information if you register for a tournament or make a purchase through our website.`,
  `We use the personal information that we collect to provide services and products to our users, including tournament registration and communication. We may also use the information for marketing purposes if you have given us your consent.`,
  `We may share your personal information with third parties such as payment processors or service providers who help us manage our website and tournaments. We will only share your information with third parties who agree to maintain the confidentiality and security of your personal information.`,
  `We take reasonable steps to protect your personal information from unauthorized access, disclosure, or loss. We use secure servers and encryption technologies to protect your information.`,
  `You can access and change your personal information by logging into your account on our website. If you have trouble accessing or changing your information, please contact our customer support team.`,
  `We may use cookies or other tracking technologies to improve our website and services. These technologies help us remember your preferences and customize your experience on our website.`,
  `We do not knowingly collect personal information from children under the age of 13. If you are under the age of 13, please do not provide us with any personal information.`,
  `Yes, you can opt out of receiving marketing emails or messages by clicking the "unsubscribe" link in the email or message. You can also contact us directly to request to be removed from our marketing list.`,
  `To  in an online game or tournament on our gaming website, you usually need to create an account and log in. Once logged in, you can browse the available games or tournaments, select the one you want to join, and follow the prompts to register or sign up. Depending on the specific game or tournament, there may be additional requirements, such as purchasing a ticket or meeting certain eligibility criteria.`,
  `The prizes or rewards for winning a tournament on our gaming website may vary depending on the specific tournament and game. They can include cash prizes, in-game currency, virtual items, or other types of rewards. The details of the prizes or rewards for each tournament are usually listed in the tournament rules or description.`,
  `If you encounter an issue or dispute during a tournament on our gaming website, you should contact the website's support or customer service team as soon as possible. Provide them with detailed information about the issue or dispute, including any relevant screenshots or evidence. The support team will investigate the matter and take appropriate actions to resolve the issue or dispute according to the website's policies and rules.`,
  `Yes, many tournaments hosted on gaming websites are open to both professional and casual gamers. Some tournaments may have different divisions or skill levels to accommodate players of various skill levels. It's important to review the tournament rules and requirements to determine if you are eligible to participate based on your gaming level or experience.`,
  `Some tournaments hosted on gaming websites may require an entry fee or charge for participation. This fee may be used to cover tournament costs, prize pools, or website maintenance. The entry fees or charges, if applicable, are usually listed in the tournament details or registration process. It's important to review and understand the fees or charges before participating in a tournament.`,
  `Depending on the tournament and game, there may be various ways to communicate with other players during the tournament, such as in-game chat, Discord, or other communication platforms. It's important to follow the tournament rules and guidelines for communication, and to be respectful and sportsmanlike when interacting with other players.`,
  `Streaming or recording tournament gameplay on our gaming website may be allowed, but it's important to review and adhere to the website's policies and rules regarding streaming or recording. Some tournaments may have specific guidelines or restrictions on streaming or recording gameplay to ensure fair competition and protect the integrity of the tournament.  `,
  `If you are unable to attend a scheduled tournament match on our gaming website, you should notify the tournament organizers or administrators as soon as possible. Depending on the specific tournament rules and circumstances, you may be disqualified from the tournament, or the match may be rescheduled. It's important to communicate promptly and follow the tournament rules for handling scheduling conflicts.`,
  `Eaque natus adipisci soluta nostrum dolorem. Nesciunt ipsum molestias ut aliquid natus ut omnis qui fugiat. Dolor et rem. Ut neque voluptatem blanditiis quasi ullam deleniti.`,
  `Nam et error exercitationem qui voluptate optio. Officia omnis qui accusantium ipsam qui. Quia sequi nulla perspiciatis optio vero omnis maxime omnis ipsum. Perspiciatis consequuntur asperiores veniam dolores.`,
  `Perspiciatis nulla ut ut ut voluptates totam consectetur eligendi qui. Optio ut cum. Dolorum sapiente qui laborum. Impedit temporibus totam delectus nihil. Voluptatem corrupti rem.`,
  `Distinctio omnis similique omnis eos. Repellat cumque rerum nisi. Reiciendis soluta non ut veniam temporibus. Accusantium et dolorem voluptas harum. Nemo eius voluptate dicta et hic nemo. Dolorem assumenda et beatae molestias sit quo mollitia quis consequatur.`,
  `Sed ut mollitia tempore ipsam et illum doloribus ut. Occaecati ratione veritatis explicabo. Omnis nam omnis sunt placeat tempore accusantium placeat distinctio velit.`,
  `Eum illo dicta et perspiciatis ut blanditiis eos sequi. Ea veritatis aut et voluptas aut. Laborum eos quia tempore a culpa.`,
  `Aut quos quae dolores repudiandae similique perferendis perferendis earum laudantium. Facere placeat natus nobis. Eius vitae ullam dolorem.`,
  `Vero dolorem et voluptatem fugit tempore a quam iure. Fuga consequatur corrupti sunt asperiores vitae. Libero totam repellendus animi debitis illum et sunt officia.`,
  `Cupiditate illum officiis id molestiae. Numquam non molestiae aliquid et natus sed hic. Alias quia explicabo sed corrupti sint. Natus in et odio qui unde facilis quia. Est sit eius laboriosam aliquid non aperiam quia quo corporis.`,
  `Et a ab. Optio aspernatur minus tempora amet vitae consectetur inventore cumque. Sed et omnis. Aspernatur a magnam.`,
  `Ipsum omnis et. Quia ea et autem tempore consequuntur veniam dolorem officiis. Ipsa dicta et ut quidem quia doloremque. Sequi vitae doloremque temporibus. Deserunt incidunt id aperiam itaque natus. Earum sit eaque quas incidunt nihil.`,
  `Quae consequatur reiciendis. Consequatur non optio. Eaque id placeat. Commodi quo officia aut repudiandae reiciendis tempore voluptatem et. Ut accusamus qui itaque maxime aliquam. Fugit ut animi molestiae porro maiores.`,
  `Modi hic asperiores ab cumque quam est aut. Voluptas atque quos molestias. Ut excepturi distinctio ipsam aspernatur sit.`,
  `Sunt totam facilis. Quam commodi voluptatem veniam. Tempora deleniti itaque fugit nihil voluptas.`,
  `Ipsam aliquam velit nobis repellendus officiis aut deserunt id et. Nihil sunt aut dolores aut. Dolores est ipsa quia et laborum quidem laborum accusamus id. Facilis odit quod hic laudantium saepe omnis nisi in sint. Sed cupiditate possimus id.`,
  `Magnam non eveniet optio optio ut aliquid atque. Velit libero aspernatur quis laborum consequatur laudantium. Tempora facere optio fugit accusantium ut. Omnis aspernatur reprehenderit autem esse ut ut enim voluptatibus.`,
  `Ipsam vel molestiae dolorem iure molestiae. Ut qui cumque et sint recusandae modi nulla. Vel rerum tempore similique autem enim voluptatem dolores facilis. Qui delectus recusandae magnam.`,
  `Fugiat molestias distinctio enim nobis rerum. Perspiciatis adipisci corrupti quas sed ab sunt nostrum. Quibusdam reiciendis ratione dolores vitae fuga exercitationem asperiores maxime voluptate. Minus et ea delectus quia ullam est. Exercitationem iusto libero. Et aut dolore reprehenderit et saepe sint modi.`,
  `Ex neque aut voluptatem delectus eum deserunt voluptate. Ut quam placeat et. Et impedit tenetur illum aut consequatur quia. Autem sed dolorem non ad aspernatur illum dignissimos beatae. Earum iusto aut rem aut. Facere ea alias enim quo assumenda.`,
  `Quis sint recusandae quasi corporis et fugit. Omnis voluptatum id laborum qui. Assumenda animi quia eum et facere fuga. Ab et sint molestiae et voluptatum nostrum est.`,
  `Est quis numquam recusandae alias porro magni. Incidunt quis aut necessitatibus nam ea dolores cumque. Quis dolorum veniam.`,
  `Corporis magnam non. Ut voluptates pariatur et. Quis tenetur mollitia et necessitatibus et. Perferendis error velit aut.`,
  `Eos ex accusantium possimus aut quae. Omnis dolorum velit. Sapiente quia dolore ea assumenda voluptatem exercitationem sed consequuntur. Eveniet et molestiae ipsa harum quidem soluta quo. Consequatur ad sunt sed numquam odio eveniet.`,
  `Ut sit et provident vero vero voluptatem distinctio. Cumque sit error qui et. Ea architecto ipsum occaecati sed alias eum vel. Officia tempore architecto autem vel veniam. Minus modi commodi ad consequatur similique ut. Tenetur tempore eum.`,
  `Quibusdam in cum voluptatem consequatur rerum. Qui eum assumenda nemo maiores veniam quae. Ipsa occaecati et provident. Quas similique deserunt doloremque placeat natus.`,
  `Voluptates et earum fugiat molestiae distinctio. Aut sapiente quas dolores et. Quo et dolor velit et iure consequatur ut in amet. Repellendus aut sequi animi inventore nesciunt itaque.`,
  `Sit a tempore dicta provident molestiae. Necessitatibus blanditiis voluptatum. Magnam esse animi in qui veritatis quibusdam recusandae adipisci possimus. Tenetur dolores ipsum.`,
  `Neque id sunt amet modi expedita aut libero aut in. Minima dolore praesentium quia quas et pariatur numquam. In ut sequi nemo velit iste minima aliquam. Neque ut tenetur consequuntur sint nemo unde. Magni nesciunt omnis illo optio. Molestias eum exercitationem aut harum odit.`,
  `Modi quia laboriosam qui ad aut. Fugit quisquam earum distinctio officia est fugit quos. Iure repellat distinctio veritatis voluptate amet ratione repudiandae.`,
  `Impedit perferendis vel quis ratione. Id aut id officia. Illum fuga saepe provident voluptate eligendi provident. Et nostrum maxime magni. Nobis cumque id magni in iste earum.`,
  `Dolor numquam maiores praesentium dolorem nihil minus praesentium rem dolorem. Est rerum placeat. Numquam sed magni aliquam laborum enim facere ducimus.`,
  `In sint enim nam et itaque et qui. Molestiae a iusto quidem quia temporibus id quia eaque eius. Quis quia consectetur saepe vero et molestias. Rem minima accusamus vitae adipisci molestiae unde voluptate consequatur molestiae. Rerum exercitationem quisquam vitae.`,
];


